name: Radar de Ofertas 24h

on:
  workflow_dispatch:
  schedule:
    # Executa a cada 2 horas
    - cron: '0 */2 * * *'

permissions:
  contents: write

jobs:
  executar_bot:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install requests

      - name: Rodar Radar de Ofertas
        run: python main.py

      - name: Salvar historico de ofertas enviadas
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ofertas_enviadas.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "Atualiza historico de ofertas [skip ci]" && git push)
